name: Java Backend Compilation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # FIX: Added a step to ensure the Maven Wrapper is executable
    - name: Permission for Wrapper
      run: chmod +x ./mvnw

    # FIX: Updated to use the Maven Wrapper (./mvnw) instead of 'mvn'
    # and ensured the build runs from the correct directory
    - name: Compile and Build with Maven Wrapper
      run: ./mvnw -B package
